<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7KVIMBF" failures="1" tests="9" name="SDET.com.sdet.App" time="110.217" errors="0" timestamp="2024-01-14T12:14:23 PST" skipped="0">
  <testcase classname="SDET.com.sdet.App" name="testLoginWithWeakPassword" time="11.380"/>
  <testcase classname="SDET.com.sdet.App" name="testLoginWithoutUsername" time="12.391"/>
  <testcase classname="SDET.com.sdet.App" name="testSignUpWithoutAge" time="11.894"/>
  <testcase classname="SDET.com.sdet.App" name="testLoginWithIncorrectAgeBelowLimit" time="11.383"/>
  <testcase classname="SDET.com.sdet.App" name="testLoginWithIncorrectAgeAboveLimit" time="11.665"/>
  <testcase classname="SDET.com.sdet.App" name="testLoginWithoutPassword" time="12.769"/>
  <testcase classname="SDET.com.sdet.App" name="testSignUpWithNumbersAndSpecialCharacterUsername" time="12.746"/>
  <testcase classname="SDET.com.sdet.App" name="testLoginWithIncorrectUsernamePasswordAndAge" time="11.249"/>
  <testcase classname="SDET.com.sdet.App" name="testSuccessfulSignUp" time="14.740">
    <failure message="expected [Welcome bella] but found [AirMirror]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Welcome bella] but found [AirMirror]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SDET.com.sdet.App.testSuccessfulSignUp(App.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- testSuccessfulSignUp -->
</testsuite> <!-- SDET.com.sdet.App -->
